export const adminKeys = {
  audit: (actionName?: string) => ["admin-audit", actionName] as const,
  bots: () => ["admin-bot-requests"] as const,
  dashboard: () => ["admin-dashboard"] as const,
  flags: () => ["admin-flags"] as const,
  me: () => ["me"] as const,
  packs: () => ["admin-sticker-packs"] as const,
  prompts: () => ["admin-prompts"] as const,
  report: (id: number) => ["admin-report", id] as const,
  reportRoot: () => ["admin-report"] as const,
  reports: (filters: { status?: string; subjectType?: string; maxAgeHours?: number }) =>
    ["admin-reports", filters] as const,
  reportsRoot: () => ["admin-reports"] as const,
  settings: () => ["admin-settings"] as const,
  strings: (query: { q?: string; surface?: string }) => ["admin-strings", query] as const,
  stringsRoot: () => ["admin-strings"] as const,
  themeAdmin: () => ["admin-theme"] as const,
  themePalette: () => ["theme-overrides"] as const,
  transcript: (conversationId: number) => ["admin-transcript", conversationId] as const,
  user: (id: number) => ["admin-user", id] as const,
  users: (q?: string) => ["admin-users", q] as const,
};
