# frozen_string_literal: true

namespace :rajya do
  desc "Export the Settings registry as JSON for the admin UI / generated TS types"
  task export_registry: :environment do
    dir = Rails.root.join("../frontend/src/shared/lib/config")
    FileUtils.mkdir_p(dir)
    payload = Settings.registry_payload
    json_path = dir.join("settings-registry.json")
    File.write(json_path, JSON.pretty_generate(payload))
    puts "Wrote #{json_path}"

    keys = payload.keys.map { |key| "  | #{key.to_json}" }.join("\n")
    dts_path = dir.join("settings-registry.d.ts")
    File.write(dts_path, <<~TS)
      /**
       * Generated by rake rajya:export_registry. Do not edit.
       * Admin UI schema: settings-registry.json (same keys).
       */
      export type SettingKey =
      #{keys};

      export interface SettingsRegistryEntry {
        type: string;
        category: string;
        default: unknown;
        description: string;
        min: number | null;
        max: number | null;
        allow_nil: boolean;
      }

      export type SettingsRegistry = Record<SettingKey, SettingsRegistryEntry>;
    TS
    puts "Wrote #{dts_path}"
  end

  # Compose and CI create the Postgres database before Rails runs, so
  # `db:prepare` migrates instead of schema:loading. Queue/cache/cable have
  # ruby schemas and no migrate/ folders — without this, solid_* tables never
  # appear and GET /health errors on solid_queue_processes.
  desc "Load Solid Queue/Cache/Cable schemas when their tables are missing"
  task ensure_solid_schemas: :environment do
    original = ActiveRecord::Base.connection_db_config
    begin
      {
        "queue" => "solid_queue_processes",
        "cache" => "solid_cache_entries",
        "cable" => "solid_cable_messages"
      }.each do |role, table|
        config = ActiveRecord::Base.configurations.configs_for(env_name: Rails.env, name: role)
        raise "No #{role} database config for #{Rails.env}" unless config

        ActiveRecord::Base.establish_connection(config)
        next if ActiveRecord::Base.connection.data_source_exists?(table)

        schema = Rails.root.join("db/#{role}_schema.rb")
        puts "Loading #{schema} (#{table} missing)"
        load schema
      end
    ensure
      ActiveRecord::Base.establish_connection(original)
    end
  end
end

Rake::Task["db:prepare"].enhance do
  Rake::Task["rajya:ensure_solid_schemas"].invoke
end
