/**
 * Generated by rake rajya:export_registry. Do not edit.
 * UI schema: preferences-registry.json (same keys).
 */
export type PreferencePath =
  | "appearance.theme"
  | "appearance.accent_light"
  | "appearance.accent_dark"
  | "appearance.split_accents"
  | "appearance.font_config_id"
  | "appearance.text_size"
  | "appearance.text_weight"
  | "appearance.text_line_height"
  | "appearance.text_letter_spacing"
  | "appearance.density"
  | "appearance.wallpaper.preset"
  | "appearance.wallpaper.dim"
  | "appearance.wallpaper.blur"
  | "appearance.bubble_corner_style"
  | "appearance.chat_font_config_id"
  | "appearance.reduce_transparency"
  | "appearance.always_show_timestamps"
  | "appearance.media_autoplay"
  | "appearance.emoji_skin_tone"
  | "locale.language"
  | "locale.timezone"
  | "locale.date_format"
  | "locale.time_format"
  | "privacy.read_receipts"
  | "privacy.last_active"
  | "privacy.discoverable_by_username"
  | "privacy.discoverable_by_email"
  | "privacy.discoverable_by_phone"
  | "privacy.show_email_on_profile"
  | "privacy.show_phone_on_profile"
  | "chat.quick_reactions"
  | "chat.enter_to_send"
  | "chat.voice_transcription_enabled"
  | "chat.link_previews_enabled"
  | "chat.save_to_gallery"
  | "chat.archive_muted_chats"
  | "ai.translation_language"
  | "ai.style_profile_enabled"
  | "ai.style_profile"
  | "ai.style_profile_updated_at"
  | "notifications.level"
  | "notifications.show_preview"
  | "notifications.sound"
  | "notifications.vibration"
  | "notifications.dnd_enabled"
  | "notifications.dnd_start"
  | "notifications.dnd_end"
  | "notifications.dnd_days";

export interface PreferenceWallpaper {
  preset: "none" | "dusk" | "mist" | "grove";
  dim: number;
  blur: number;
}

export interface PreferenceAppearance {
  theme: "light" | "dark" | "system";
  accent_light: string;
  accent_dark: string;
  split_accents: boolean;
  font_config_id: number | null;
  text_size: number;
  text_weight: number;
  text_line_height: number;
  text_letter_spacing: number;
  density: "comfortable" | "compact";
  wallpaper: PreferenceWallpaper;
  bubble_corner_style: "rounded" | "square";
  chat_font_config_id: number | null;
  reduce_transparency: boolean;
  always_show_timestamps: boolean;
  media_autoplay: "always" | "wifi_only" | "never";
  emoji_skin_tone: number;
}

export interface PreferenceLocale {
  language: string;
  timezone: string;
  date_format: "YYYY-MM-DD" | "MM/DD/YYYY" | "DD/MM/YYYY" | "DD-MM-YYYY" | "MMM D, YYYY" | "D MMM YYYY" | "MMMM D, YYYY" | "D MMMM YYYY" | "ddd, MMM D, YYYY" | "MM.DD.YYYY" | "DD.MM.YYYY";
  time_format: "12h" | "24h";
}

export interface PreferencePrivacy {
  read_receipts: boolean;
  last_active: boolean;
  discoverable_by_username: boolean;
  discoverable_by_email: boolean;
  discoverable_by_phone: boolean;
  show_email_on_profile: boolean;
  show_phone_on_profile: boolean;
}

export interface PreferenceChat {
  quick_reactions: string[];
  enter_to_send: boolean;
  voice_transcription_enabled: boolean;
  link_previews_enabled: boolean;
  save_to_gallery: boolean;
  archive_muted_chats: boolean;
}

export interface PreferenceAi {
  translation_language: string;
  style_profile_enabled: boolean;
  style_profile: Record<string, unknown> | null;
  style_profile_updated_at: string | null;
}

export interface PreferenceNotificationScope {
  level: "all" | "mentions" | "none";
  show_preview: boolean;
  sound: boolean;
  vibration: boolean;
  dnd_enabled: boolean;
  dnd_start: string;
  dnd_end: string;
  dnd_days: number[];
}

export type PreferenceNotifications = {
  global: PreferenceNotificationScope;
} & Record<string, PreferenceNotificationScope>;

export interface PreferenceDocument {
  appearance: PreferenceAppearance;
  locale: PreferenceLocale;
  privacy: PreferencePrivacy;
  chat: PreferenceChat;
  ai: PreferenceAi;
  notifications: PreferenceNotifications;
}

export interface PreferenceFieldSchema {
  type: string;
  default: unknown;
  values?: string[];
  min?: number;
  max?: number;
  allow_nil?: boolean;
  format?: string;
  of?: string;
  size?: number;
  max_item_length?: number;
  scoped?: boolean;
  scopes?: string[];
}

export type PreferenceRegistry = Record<PreferencePath, PreferenceFieldSchema>;
